spring.application.name=Gestion_Reservas
# 1. URL de conexión a tu base de datos en Neon
spring.datasource.url=jdbc:postgresql://ep-morning-cherry-ac7zgf9t-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
# 2. Credenciales exactas que me compartiste
spring.datasource.username=neondb_owner
spring.datasource.password=npg_1ObNZvsyR5fu
# 3. Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 5. Opcional: Muestra en la consola de VS Code cómo se crean las tablas
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
spring.resources.static-locations=classpath:/static/
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet=DEBUG

# JWT config (Base64; minimo 256 bits para HS256)
jwt.secret=MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
jwt.expiration.ms=36000000

